### ISSUE TITLE
write recipes in hackpad

### ISSUE THREAD

**Issue by basiacierocka** [Ragnarson-Internship2016/group-IV#36]

**Comment by gosiamaks** [comment]
or just copy them from some page :)

**Comment by ghost** [comment]
https://hackpad.com/Our-recipes-SmeSjg8C685

**Comment by wozane** [comment]
Great list of recipes!
Just to confirm. As per model, we should have in our recipe:
- name
- description
  Will the link be as a description of the recipe or should we add it?

**Comment by agatasalska** [comment]
up 2 you, description is a text field. I would suggest giving the exact mode of preparation there.

**Comment by gotar** [comment]
close it if ready

**Comment by gosiamaks** [comment]
@jeathli If you refer to the subpage with one specific recipe, I would copy and put there the content (text with the recipe description, not only link).
