### ISSUE TITLE
Layout: add links to navbar

### ISSUE THREAD

**Issue by abukowska** [Ragnarson-Internship2016/group-IV#37]
thanks to that the user could get back to the main paige using button on the page

**Comment by CallMeSandra** [comment]
Something like "back to main page" button, right?

**Comment by gosiamaks** [comment]
in navbar you have buttons which are in every page (they're situated in layout); they are: HOME, RECIPES (page with listed all recipes), RANDOM! (page with the view of one random recipe). "Back" button will appear either way on every page, but it's not in main layout.
